name: app_center_plugin
description: A Flutter Plugin for AppCenter with Analytics and Crashes, you can track events and errors easily.
version: 2.0.1
repository: https://github.com/Eronildo/app_center
homepage: https://github.com/Eronildo/app_center
topics: [appcenter, analytics, crashlytics, track, events]

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  stack_trace: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.eronildo.app_center
        pluginClass: AppCenterPlugin
      ios:
        pluginClass: AppCenterPlugin
